Valores campo ST
1 = ATIVO
2 = CANCELADO

Valores campo TIPO_CONTA
1 = BANCO
2 = CAIXA
3 = APLICAÇÃO

Valores campo TIPO_MOVIMENTO
1 = CREDITO_A_VISTA
2 = DEBITO_A_VISTA
3 = CREDITO_A_PRAZO
4 = DEBITO_A_PRAZO
5 = QUITACAO_DE_CREDITO
6 = QUITACAO_DE_DEBITO

Valores campo PARCELADO
1 = SIM
2 = NAO

Valores campo TIPO_FIXO
1 = PROVENTO
2 = DESCONTO

Valores campo PERIODICIDADE
1 = SEMANAL
2 = MENSAL
3 = ANUAL

Valores campo TIPO_PARCELA
1 = QUITADO
3 = CREDITO_A_PRAZO
4 = DEBITO_A_PRAZO